services:
  carmind-backend:
    build:
      context: .
    ports:
      - "PUT_YOUR_PORT_HERE:3000"
    volumes:
      - ./appdb:/usr/src/app/prisma/data
      - ./appuploads:/usr/src/app/uploads
    environment:
      - DATABASE_URL=file:./data/dev.db
      - FRONT_END_URL=PUT_YOUR_URL_FOR_THE_FRONTEND
      - SESSION_SECRET=PUT_YOUR_SESSION_SECRET
      - COOKIE_SECRET=PUT_YOUR_COOKIE_SECRET
      - PORT=3000
      - VAPID_PUBLIC_KEY=PUT_PUBLIC_VAPID_KEY_HERE
      - VAPID_PRIVATE_KEY=PUT_PRIVATE_VAPID_KEY_HERE
      - VAPID_EMAIL="PUT_YOUR_VAPID_EMAIL_HERE"
